# yamllint disable rule:document-start

#########################################################
#
#   GARAGE DOOR SENSOR
#
#########################################################

# --- Garage Door Open/Closed Badge----------------------
- platform: template
  sensors:
    garage_door_badge:
      value_template: >-
        {{states("sensor.garage_door_state") | title}}
      entity_picture_template: >-
        {% if is_state("sensor.garage_door_state", "open") %}
          /local/garage-door-open.png
        {% else %}
          /local/garage-door-closed.png
        {% endif %}

# --- Garage Door Open/Closed State ---------------------
- platform: template
  sensors:
    garage_door_state:
      friendly_name: Garage Door State
      value_template: >
        {% if is_state("binary_sensor.garage_door_sensor_contact", "on") %}
          open
        {% else %}
          closed
        {% endif %}

